language: cpp

compiler:
 - clang
 - gcc

env:
 - config=debug64   config_suffix=debug_x64_gmake
 - config=release64 config_suffix=release_x64_gmake

before_install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update -qq
  - sudo apt-get install -y premake4

install: true

before_script:
  - cd build 
  - premake4 'gmake'
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - make -C build/gmake -f test.make
  - make -C build/gmake -f example.make 
  - cd bin
  - ./unittest_${config_suffix}
  - ./perftest_${config_suffix}
